# Generated by Django 4.1.1 on 2022-10-12 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.IntegerField(default=1, verbose_name='پوزیشن'),
            preserve_default=False,
        ),
    ]
