# Generated by Django 4.1 on 2022-10-19 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_article_category_delete_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'مرور', 'verbose_name_plural': 'مرورها'},
        ),
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
        migrations.RemoveField(
            model_name='article',
            name='publish',
        ),
        migrations.RemoveField(
            model_name='article',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='article',
            name='status',
        ),
        migrations.RemoveField(
            model_name='article',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='article',
            name='updated',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
