# Generated by Django 4.1.1 on 2022-10-19 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_article_options_remove_article_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='test_int',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
